# =========================
# DEPLOYMENT
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agrocoredados
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agrocoredados

  template:
    metadata:
      labels:
        app: agrocoredados

    spec:
      containers:
        - name: agrocoredados
          image: euturial/agrocoredados:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

---
# =========================
# SERVICE (ClusterIP)
# =========================
apiVersion: v1
kind: Service
metadata:
  name: agrocoredados
spec:
  type: ClusterIP

  selector:
    app: agrocoredados

  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080

---
# =========================
# SERVICEMONITOR
# =========================
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-agrocoredados-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: agrocoredados
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
# =========================
# INGRESS
# =========================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agrocoredados-ingress

  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  ingressClassName: nginx

  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: agrocoredados
                port:
                  number: 80
